#!/bin/bash

set -e

create() {
  newEntry() {
    headerText="$@"
    result="${TEMPLATE_TEXT}"
    result="${result/HEADERTEXT/$headerText}"
    result="${result/TIMESTAMP/$timestamp}"
    echo -e "\n$result\n"
  }
  TEMPLATE_TEXT=""
  if [ -f "${NOTED_TEMPLATE_FILE}" ]; then
    # use template file
    TEMPLATE_TEXT=$(<"${NOTED_TEMPLATE_FILE}")
  else
    read -r -d '' TEMPLATE_TEXT <<EOF || true
TIMESTAMP: HEADERTEXT
EOF
  fi
  mkdir -p "${NOTED_MARKDOWN_HOME}"
  markdownFile "${currDate}"
  if [[ ! -f "${markdownFile}" ]]; then
	echo "---" >> $markdownFile
	echo "title: ${currDate}" >> $markdownFile
	echo "date: ${currDate} ${timestamp}" >> $markdownFile
	echo "description: Here is a little bit about my post." >> $markdownFile
	echo "type: post" >> $markdownFile
	echo "# cover_image: ./images/img.jpg" >> $markdownFile
	echo "published: true" >> $markdownFile
	echo "tags: [Diary] # , Friday, Picnic, Book, MovieNight" >> $markdownFile
	echo "---" >> $markdownFile
	echo "" >> $markdownFile
	echo "# ${currDate}" >> $markdownFile
	echo "" >> $markdownFile
	echo "## What I have accomplished" >> $markdownFile
	echo "" >> $markdownFile
	echo "## What I have learned" >> $markdownFile
	echo "" >> $markdownFile
	echo "## What should I do tomorrow" >> $markdownFile
	echo "" >> $markdownFile
	echo "## My Ideas during the day !" >> $markdownFile
	echo "" >> $markdownFile
	echo "## Today's Log" >> $markdownFile
  fi
  touch "${markdownFile}"
  if [ -n "${OPTIONAL_NOTE}" ]; then
    # Supplying a note means automatically add that to the file
    newEntry "${OPTIONAL_NOTE}" >>"${markdownFile}"
  else
    # otherwise open it up with the template and let them edit
    newEntry >>"${markdownFile}"
    edit "${markdownFile}"
  fi
}

edit() {
  vim "${markdownFile}"
}

loadProperties() {
  if [[ -f "${CONFIG_FILE}" ]]; then
    source "${CONFIG_FILE}"
  fi
}

markdownFile() {
  YEAR="`date +%Y`"
  MONTH="`date +%m`"
  markdownFile="${NOTED_MARKDOWN_HOME}/${YEAR}/${MONTH}/${1}.md"

}

ngrep() {
  grep --recursive "$@" "${NOTED_MARKDOWN_HOME}"
}

outputConfig() {
  echo "The following configuration is currently being used:"
  echo "NOTED_MARKDOWN_HOME=${NOTED_MARKDOWN_HOME}"
  echo "NOTED_FILE_NAME_DATE_FORMAT=${NOTED_FILE_NAME_DATE_FORMAT}"
  echo "NOTED_TIMESTAMP_FORMAT=${NOTED_TIMESTAMP_FORMAT}"
  echo "NOTED_TEMPLATE_FILE=${NOTED_TEMPLATE_FILE:-<<DEFAULT>>}"
}

validate() {
  if [ -z "$1" ]; then
    echo "${2}"
    exit 1
  fi
}

version() {
  echo "noted v${VERSION}"
}

view() {
  less "${markdownFile}"
}

#
# END FUNCTIONS
#

VERSION="0.0.3"

#
# Default Settings
#
# Settings that cannot be overridden
# Location of config file
CONFIG_FILE=$HOME/.notedconfig

# Settings that can be overridden from properties
# name files like this
NOTED_FILE_NAME_DATE_FORMAT="+%Y-%m-%d"
# timestamp entries within the files like this
NOTED_TIMESTAMP_FORMAT="+%H:%M:%S"
NOTED_TEMPLATE_FILE=""
# keep the directory where notes are stored here
NOTED_MARKDOWN_HOME=D:/Polla/PollaFattah/Life/personalBlog

#
# Override with any additional settings
#
loadProperties

currDate=$(date "${NOTED_FILE_NAME_DATE_FORMAT}")
timestamp=$(date "${NOTED_TIMESTAMP_FORMAT}")

todaysFile="${NOTED_MARKDOWN_HOME}/${currDate}.md"

subcommand="$1"
if  [[ "${subcommand}" == "config" ]]; then
  outputConfig
elif [[ "${subcommand}" == "version" ]]; then
  version
elif [[ "${subcommand}" == "view" ]]; then
  arg="$2"
  if [[ -z "${arg}" ]]; then
    arg="${currDate}"
  fi
  markdownFile "${arg}"
  echo "${markdownFile}"
  view "${markdownFile}"
elif [[ "${subcommand}" == "edit" ]]; then
  arg="$2"
  if [[ -z "${arg}" ]]; then
    arg="${currDate}"
  fi
  markdownFile "${arg}"
  edit "${markdownFile}"
elif [[ "${subcommand}" == "grep" ]]; then
  shift
  ngrep "$@"
else
  # create / default
  OPTIONAL_NOTE=""
  if [[ "${subcommand}" == "create" ]]; then
    shift
  fi
  if [[ -n "$1" ]]; then
    OPTIONAL_NOTE="$1"
  fi
  create "${OPTIONAL_NOTE}"
fi
